# Reader's guide {.unnumbered}

## Country codes {.unnumbered}

In some tables and graphs countries are referred to by their three-letter
ISO 3166-1 country codes, the codes for the 38 countries covered by the
2019 InCiSE Index are:

Code| Country
:-: | :--
AUS | Australia
AUT | Austria
BEL | Belgium
BGR | Bulgaria
CAN | Canada
CHL | Chile
HRV | Croatia
CZE | Czechia
DNK | Denmark
EST | Estonia
FIN | Finland
FRA | France
DEU | Germany
GRC | Greece
HUN | Hungary
ISL | Iceland
IRL | Ireland
ISR | Israel
ITA | Italy
JPN | Japan
KOR | Korea (the Republic of)
LVA | Latvia
LTU | Lithuania
MEX | Mexico
NLD | Netherlands (the)
NZL | New Zealand
NOR | Norway
POL | Poland
PRT | Portugal
ROU | Romania
SVK | Slovakia
SVN | Slovenia
ESP | Spain
SWE | Sweden
CHE | Switzerland
TUR | Turkey
GBR | United Kingdom
USA | United States of America (the)

: {tbl-colwidths="[25, 75]" .striped .sm}

## Indicator codes {.unnumbered}

The following acronyms are used in some tables to refer to the 12 indicators
measured in the InCiSE 2019 Index.

Code | Indicator
:-: | :--
CAP | Capabilities
CRM | Crisis and risk management
DIG | Digital services
FFM | Fiscal and financial management
HRM | HR management
INC | Inclusiveness
INT | Integrity
OPN | Openness
POL | Policy making
PRO | Procurement
REG | Regulation
TAX | Tax administration

: {tbl-colwidths="[25, 75]" .striped .sm}
