---
execute:
  echo: false
  warning: false
---

# Results of the 2019 InCiSE Index {#sec-index-results}

This chapter presents the overall results of the 2019 edition of the InCiSE
Index. In addition, it provides a summary of results for each of the 12
indicators, including the top five country rankings. The
[country profiles](04_00_country_profiles.qmd) part provides a summary of
each country's results, while tables of country scores
and rankings are provided at @sec-scores-rankings.

Developing a comprehensive range of indicators means that there is often a wide
variation in how countries perform against each of them. The overall scores for
the top 3 countries in the Index are very close. No country consistently
appears in the top 5 positions for every indicator, although there are some good
all-round performers. These are highlighted in the individual country
assessments. There are also some stand-out country scores for specific
indicators and these have been highlighted.

All scores in the InCiSE results are relative, meaning that the highest scoring
country is assigned 1.0 and the lowest scoring country is assigned 0.0.
Relative scores do not directly translate to absolute performance; a score of
1.0 or 0.0 does not mean in absolute terms that a country is high or low
performing. Rather, of the 38 countries selected they have the highest and
lowest performance within that group of countries. The methodology used to
explain these scores is explained in the Technical Report.

::: {.callout-tip title="Interactive content" icon="false"}
This charts in this chapter are interactive and may not be fully accessible,
a [static version](Y_results_static.qmd) of this chapter is available in the
Appendices to this report. Depending on your network connection it may take a
few seconds for the charts to load properly.

When this page is first loaded one of the 38 countries covered by the InCiSE
Index is selected at random, to change the selection either use the drop down
menu or click on the country's position in the bar chat.

The following content is interactive and may not be fully accessible,
a [static version](Y_results_static.qmd) of this chapter is available in the
Appendices to this report.
:::

## Overall scores and rankings for the InCiSE Index {#sec-rankings}

The charts shows the overall InCiSE Index scores. The bar chart on the left
shows the results of the InCiSE Index for all 38 countries. The radar chart
on the right shows the InCiSE average score (in green) and the upper and lower
quartile country scores (in grey) for each of the 12 InCiSE Indicators.

```{ojs, setup}
//| output: false

Plot = import("https://esm.sh/@observablehq/plot")

bar_data = FileAttachment("country_visuals/bar_data_full.csv").csv({ "typed": true });
radar_grid = FileAttachment("country_visuals/radar_grid.csv").csv({ "typed": true });
radar_axes = FileAttachment("country_visuals/radar_axes.csv").csv({ "typed": true });
radar_data = FileAttachment("country_visuals/radar_incise.csv").csv({ "typed": true });
radar_full = FileAttachment("country_visuals/radar_data_full.csv").csv({ "typed": true });

bar_index = bar_data.filter(function(df){
  return "incise_index" == df.indicator
});

bar_incise = bar_index.filter(function(df){
  return "InCiSE" == df.cc_iso3c
});

country_radar = radar_full.filter(function(df){
  return "incise_index" != df.indicator && "InCiSE" != df.cc_iso3c
});

chart_curve = "catmull-rom-closed"

indicator_bar = function(ind) {
  
  var ind_bar_df = bar_data.filter(function(df){
    return ind == df.indicator
  });
  
  var ind_bar_incise = ind_bar_df.filter(function(df){
    return "InCiSE" == df.cc_iso3c
  });
  
  var ind_plot = Plot.plot({
    width: 300,
    height: 600,
    marginLeft: 50,
    marginTop: 0,
    style: {fontSize: 11},
    x: {label: null, grid: true, domain: [0, 1.1]},
    y: {label: null, axis: null},
    color: {type: "identity"},
    marks: [
      Plot.barX(ind_bar_df, {
        x: "value",
        y: "cc_iso3c",
        sort: {y: "x", reverse: true},
        fill: "colour_group"
      }),
      Plot.text(ind_bar_df, {
        x: -0.05,
        y: "cc_iso3c",
        text: "cc_iso3c",
        fill: "text_colour",
        textAnchor: "end",
        fontWeight: "600",
        filter: (d) => "bold" == d.text_weight,
        sort: {y: "x", reverse: true}
      }),
      Plot.text(ind_bar_df, {
        x: -0.05,
        y: "cc_iso3c",
        text: "cc_iso3c",
        fill: "text_colour",
        textAnchor: "end",
        filter: (d) => "normal" == d.text_weight,
        sort: {y: "x", reverse: true}
      }),
      Plot.text(ind_bar_incise, {
        x: (d) => d.value + 0.05,
        y: "cc_iso3c",
        text: "value_label",
        fill: "#C4622D",
        fontWeight: "600",
        textAnchor: "start",
        sort: {y: "x", reverse: true}
      }),
      Plot.tip(ind_bar_df,
        Plot.pointerY({
          x: "value",
          y: "cc_iso3c",
          filter: (d) => d.hover_label,
          title: (d) => d.hover_label,
          frameAnchor: "left"
        })
      )
    ]
  });
  
  return ind_plot
  
};

viewof hover_country = Inputs.input(null);

hover_data = country_radar.filter(function(df){
  return hover_country == df.cc_iso3c
});

viewof hover_value = Inputs.input(null);
viewof hover_ind = Inputs.input(null);

set_val = function(input, value) {
  input.value = value;
  input.dispatchEvent(new Event("input"))
};

indicator_summary.addEventListener("input", (event) => {
  if (indicator_summary.value != null) {
    if (indicator_summary.value.cc_iso3c != "InCiSE") {
      set_val(viewof hover_country, indicator_summary.value.cc_iso3c)
      set_val(viewof hover_value, indicator_summary.value.raw_value)
      set_val(viewof hover_ind, indicator_summary.value.indicator)
    }
  } else {
    set_val(viewof hover_country, null)
  }
});

incise_radar = radar_full.filter(function(df){
  return "InCiSE" == df.cc_iso3c
})

```

::: {layout="[ [4,8] ]"}
```{ojs, incise_bar}
bar_plot = Plot.plot({
  width: 250,
  height: 500,
  marginLeft: 50,
  style: {fontSize: 11},
  x: {label: null, grid: true, domain: [-0.2, 1.1]},
  y: {label: null, axis: null},
  color: {type: "identity"},
  marks: [
    Plot.barX(bar_index, {
      x: "value",
      y: "cc_iso3c",
      fill: "colour_group",
      sort: {y: "x", reverse: true}
    }),
    Plot.text(bar_index, {
      x: -0.05,
      y: "cc_iso3c",
      text: "cc_iso3c",
      fill: "text_colour",
      textAnchor: "end",
      fontWeight: "600",
      filter: (d) => "bold" == d.text_weight,
      sort: {y: "x", reverse: true}
    }),
    Plot.text(bar_index, {
      x: -0.05,
      y: "cc_iso3c",
      text: "cc_iso3c",
      fill: "text_colour",
      textAnchor: "end",
      filter: (d) => "normal" == d.text_weight,
      sort: {y: "x", reverse: true}
    }),
    Plot.text(bar_incise, {
      x: (d) => d.value + 0.05,
      y: "cc_iso3c",
      text: "value_label",
      fill: "#C4622D",
      fontWeight: "600",
      textAnchor: "start",
      sort: {y: "x", reverse: true}
    }),
    Plot.tip(bar_index,
      Plot.pointerY({
        x: "value",
        y: "cc_iso3c",
        filter: (d) => d.hover_label,
        title: (d) => d.hover_label,
        frameAnchor: "left"
      })
    )
  ]
});

```

```{ojs, incise_radar}
radar_plot = Plot.plot({
  width: 500,
  height: 500,
  style: {fontSize: 11},
  x: {domain: [-1.5, 1.5], label: null, axis: null},
  y: {domain: [-1.5, 1.5], label: null, axis: null},
  color: {
    type: "categorical",
    domain: ["InCiSE average", "Lower quartile", "Upper quartile"],
    range: ["#C4622D", "#bbbbbb", "#bbbbbb"]
  },
  marks: [
    Plot.line(radar_grid, {
      x: "grid_x",
      y: "grid_y",
      z: "grid",
      stroke: "#dddddd",
      curve: chart_curve
    }),
    Plot.link(radar_axes, {
      x1: 0,
      y1: 0,
      x2: "axis_x",
      y2: "axis_y",
      z: "indicator",
      stroke: "#dddddd",
      curve: "linear"
    }),
    Plot.line(radar_data, {
      x: "new_x",
      y: "new_y",
      z: "cc_iso3c",
      stroke: "cc_iso3c",
      strokeWidth: 2,
      curve: chart_curve
    }),
    Plot.dot(radar_data, {
      x: "new_x",
      y: "new_y",
      z: "cc_iso3c",
      fill: "cc_iso3c",
      symbol: "circle-stroke",
      strokeWidth: 2
    }),
    Plot.text(radar_axes, {
      x: "label_x",
      y: "label_y",
      text: "indicator"
    }),
    Plot.tip(radar_data,
      Plot.pointer({
        x: "new_x",
        y: "new_y",
        filter: (d) => d.data_label,
        title: (d) => d.data_label
      })
    )
  ]
});   

```

:::

The chart below shows the distribution of country scores for each indicator.
Country scores are shown as blue dots, the lowest scoring country is on the
left hand-side and the highest scoring country on the right hand-side (the
country code is also shown to the right of each line). The InCiSE average for
each indicator is shown by an orange vertical bar.

```{ojs, indicator_summary}

indicator_summary = Plot.plot({
  width: 750,
  height: 500,
  marginLeft: 100,
  marginRight: 100,
  style: {fontSize: 11},
  x: {domain: [0, 1.1], grid: true, label: null},
  y: {label: null},
  marks: [
    Plot.gridY(country_radar, {
      x1: 0,
      x2: 1,
      y: "indicator",
      z: "indicator",
      stroke: "#eeeeee",
      strokeWidth: 10
    }),
    Plot.text(incise_radar, {
      x: "raw_value",
      y: "indicator",
      text: ["|", "|", "|", "|", "|", "|", "|", "|", "|", "|", "|", "|"],
      stroke: "#C4622D"
    }),
    Plot.dot(country_radar, {
      x: "raw_value",
      y: "indicator",
      symbol: "circle",
      fill: "#00629B",
      opacity: 0.25
    }),
    Plot.dot(country_radar, {
      x: "raw_value",
      y: "indicator",
      symbol: "circle",
      stroke: "#00629B",
      strokeWidth: 0.5,
      opacity: 1
    }),
    Plot.dot(country_radar,
      Plot.groupY ({x: "min"}, {
        x: "raw_value",
        y: "indicator",
        z: "indicator",
        symbol: "circle",
        fill: "#00629B",
        opacity: 1
      })
    ),
    Plot.dot(country_radar,
      Plot.groupY ({x: "max"}, {
        x: "raw_value",
        y: "indicator",
        z: "indicator",
        symbol: "circle",
        fill: "#00629B",
        opacity: 1
      })
    ),
    Plot.text(country_radar,
      Plot.selectMaxX ({
        x: "raw_value",
        y: "indicator",
        z: "indicator",
        text: "cc_iso3c",
        textAnchor: "start",
        fill: "#00629B",
        dx: 10,
      })
    ),
    Plot.dot(hover_data, {
      x: "raw_value",
      y: "indicator",
      symbol: "circle",
      stroke: "#002147",
      r: 6
    }),
    Plot.text(hover_data, {
      x: "raw_value",
      y: "indicator",
      text: "cc_iso3c",
      filter: (d) => hover_value == d.raw_value && hover_ind == d.indicator,
      fill: "#002147",
      dy: -15
    }),
    Plot.dot(country_radar, 
      Plot.pointer({
        x: "raw_value",
        y: "indicator",
        opacity: 0
      })
    )
  ]
});

```

The following sections summarise the scores for each of the 12 indicators
measured in InCiSE 2019, each section includes a bar chart showing the scores
for each country (in grey) and the InCiSE average (in orange), the scores of
the five highest scoring countries are also highlighted (in blue).

## Policy making {#sec-policy-making}

::: {layout="[35,60]"}
```{ojs, ind-pol}
indicator_bar("ind_pol")
```

This indicator has 4 themes: the quality of policy advice; the degree of
strategic planning; the coordination of policy proposals across government;
and the degree of policy monitoring during implementation. This indicator is
comprised of 8 metrics and its structure is unchanged from 2017. It uses a
single data source, the Bertelsmann Stiftung's Sustainable Government
Indicators (SGI). The policy making scores for all countries in the top 5 are
very close. The UK's and Canada's scores are highest out of the top 5 on the
quality of policy advice theme, while Finland's and Denmark's scores are
highest on strategic planning. There is greater variation between these
countries for the policy monitoring theme, with Denmark and Canada scoring
highest for 2 out of the 3 metrics. It is noteworthy that 4 out of the top 5
countries ranked for the policy making indicator also feature in the top 5 of
the main InCiSE Index, while Denmark is ranked 6th overall.
:::


## Fiscal and financial management {#sec-fiscal}

::: {layout="[65,35]"}

This indicator has 3 themes: the effectiveness of public spending; the
transparency of public spending; and budget practices. There are 6 metrics
(an increase of 3 since 2017) and 4 data sources: the World Economic Forum's
Global Competitiveness Index (GCI); the OECD's Medium-Term Budgeting Index
and PerformanceBudgeting Index; The World Bank's Financial Management
Information Systems and OpenBudget Data; and the International Budget
Partnership's Open Budget Survey. The top 2 country scores are very close,
with the Republic of Korea edging ahead because of its very high scores for the
transparency of public spending and budget practices themes. Germany has the
highest score out of the top 5 for the effectiveness of public spending theme.
New Zealand comes top for the metric looking at the openness of the budgeting
process. Sweden's highest scores are for open budgeting and performance
budgeting, while the UK's scores for performance budgeting are high as well.

```{ojs, ind-ffm}
indicator_bar("ind_ffm")
```

:::

## Regulation {#sec-regulation}

::: {layout="[35,65]"}
```{ojs, ind-reg}
indicator_bar("ind_reg")
```

This indicator has 3 themes relating to regulation policies and management:
the use of appraisal and evaluation; the extent of stakeholder engagement;
and the nature of impact assessment. There are 9 metrics (an increase of 3
since 2017) and 2 data sources: the OECD's Indicators of Regulatory Policy
and Governance; and the Bertelsmann Stiftung's Sustainable Governance
Indicators (SGI). Amongst the top 5 countries for this indicator, the UK
achieves the maximum score for 4 metrics. These are spread across all themes,
suggesting a strong performance across the board for this core function. New
Zealand achieves the maximum score for 2 metrics: the use of impact assessments
in regulatory work; and the quality of impact assessments. As in 2017, Mexico's
strong performance may reflect the country's long-standing focus on regulatory
policy reforms. It achieves the maximum score for one of the two stakeholder
engagement metrics and scores very highly against the other one. Mexico
achieves very high scores for two of the appraisal and evaluation metrics
as well.
:::

## Crisis and risk management {#sec-crisis-risk}

::: {layout="[65,35]"}

This indicator has 4 themes regarding disaster risk reduction and management
issues most relevant for the civil service: the degree of strategic approach to
risk; the degree of preparedness; communications; and evaluation. This
indicator has been significantly restructured to take account of feedback
following the pilot report. There are now 13 metrics (an increase of 4 since
2017) and 2 data sources (one more than in 2017): the UN Hyogo Framework for
Action monitoring reports; and the OECD's Survey on the Governance of Critical
Risk. The top 3 country scores for this indicator are all very close while the
other 2 countries are not far behind. Scores for the metrics in this indicator
are close for many countries, which is largely because of the nature of the
source data. This also means that for some metrics a large number of countries
score highly. Conversely, for a few metrics only a small number of countries
score well. The Netherlands' top position reflects consistently strong scores
across almost all metrics, ranking joint top for 10 metrics. Sweden ranks joint
top for 9 metrics, while Finland ranks joint top for 11 metrics.

```{ojs, ind-crm}
indicator_bar("ind_crm")
```

:::

## Human resource management {#sec-hrm}

::: {layout="[35,65]"}
```{ojs, ind-hrm}
indicator_bar("ind_hrm")
```

This indicator now measures 4 themes, an increase of 2 since 2017: the extent
to which civil service recruitment systems are meritocratic; attracting and
retaining talent; performance management systems and practices; and the extent
of human resources (HR) data collection. There are now 9 metrics, an increase
of 4 since 2017, and 2 data sources (previously just one): the Quality of
Government expert survey by the University of Gothenburg's Quality of
Government survey; and the OECD's survey on Strategic Human Resources
Management. The indicator scores for the first 4 countries are all very close,
although specific metrics scores vary widely. Canada only just surpasses
Ireland for the top position. This is mainly because of its relatively higher
score for the metric which assesses the extent to which separate HR management
practices are in place for senior civil servants. The Republic of Korea's score
is the highest out of the top 5 countries for the metric which assesses the
extent to which databases are used for HR management. Of this group, Japan
achieves the top score for the extent to which performance assessments are
used in HR decision making.
:::

## Tax administration {#sec-tax}

::: {layout="[65,35]"}
This indicator measures 3 themes: the overall efficiency of tax collection;
the extent to which services are user focused; and the extent and the quality
of digital provision. The data sources are the OECD's Tax Administration Survey
and The World Bank's Doing Business Index (DBI). This indicator is comprised
of 6 metrics and its structure is unchanged from the 2017 Pilot. Estonia's
indicator score is noticeably ahead of the other countries in this table and
it consistently achieves very high scores across all 6 metrics. Within the
top 5 countries, Estonia achieves the top score for the metrics assessing
the volume of online VAT and personal tax returns, as well as for the metric
on the extent to which services are user focused. Ireland achieves a very
high score for one of the efficiency metrics (total tax debt as a proportion
of net revenue), as well as metrics measuring the volume of online VAT and
corporate tax returns. The UK and the Netherlands achieve very high scores for
these three metrics as well, while Norway achieves very high scores for two of
them (tax debt proportion and online VAT returns).

```{ojs, ind-tax}
indicator_bar("ind_tax")
```
:::

## Digital Services {#sec-digital-services}

::: {layout="[35,65]"}
```{ojs, ind-dig}
indicator_bar("ind_dig")
```

This indicator measures 3 themes: user experience; cross-border availability of
services; and the availability of "key enablers" (the enabling infrastructure
for digital service provision, such as electronic ID cards). The sole data
source is the European Commission's E-Government Benchmark Report. Significant
changes have been made to the way in which the data for this indicator has
been compiled. In addition, it is now composed of 13 metrics – there were only
4 metrics in the 2017 Pilot. The indicator scores for the top 4 countries are
all very close, with Denmark and Latvia achieving the same overall score.
Estonia's top position may reflect consistently high scores across most
metrics. Amongst the top 5 countries, Austria achieves the highest scores for
the metrics focusing on the availability and accessibility of online small
claims procedures, including for non-nationals. Denmark achieves the maximum
score for six metrics and these are spread across all themes, while Portugal
achieves the maximum score for four metrics. Latvia's results are all above
average and it achieves the maximum score for a metric within the "key enabler"
theme.
:::

## Procurement {#sec-procurement}

::: {layout="[65,35]"}
This indicator is a new addition to the Index. There are two themes:
procurement systems and procurement practices. It is comprised of 6 metrics
and 2 data sources: the OECD's Public Procurement Survey; and analysis of
European public procurement data from the Opentender project of the
Digiwhist collaboration. The indicator scores for the top 3 countries in this
table are significantly ahead of the others. New Zealand's top position is
primarily because it achieves the maximum score for three metrics: the extent
of e-procurement functions within its overall procurement system; the role of
its central purchasing body; and the extent to which policies are in place to
enable small and medium-sized enterprises (SME) to take part in central
government procurement. The UK and Israel achieve the maximum score for the
SME participation metric as well, while Denmark achieves the maximum score
for the metric assessing the role of its central purchasing body. The Republic
of Korea's highest score is for the e-procurement metric.

```{ojs, ind-pro}
indicator_bar("ind_pro")
```
:::

## Integrity {#sec-integrity}

::: {layout="[35,65]"}
```{ojs, ind-int}
indicator_bar("ind_int")
```

This indicator covers 6 themes: corruption level perceptions; adherence to
rules and procedures; work ethics; fairness and impartiality; striving to
serve citizens and ministers; and processes in place to preserve integrity and
prevent conflicts of interest. There are 17 metrics (one more than in 2017)
and 5 data sources: the Bertelsmann Stiftung's SGIs; Transparency
International's Global Corruption Barometer; the World Economic Forum's
Global Competitiveness Report Executive Opinion Survey; the University of
Gothenburg's Quality of Government Expert Survey Data; and results from two
OECD surveys published in their Government at a Glance report. New Zealand's
overall score is well ahead of all other countries, reflecting a strong
performance against most metrics. It achieves the maximum score for 8 of the
metrics. Canada achieves the maximum score for the metric which assesses public
perceptions of impartiality in the civil service. It also achieves the maximum
score for having a post-employment cooling off period. Sweden's score for the
metric which assesses the degree of whistle-blower protection for employees is
noticeably ahead of all other countries in the top 5 table.
:::

## Openness {#sec-openness}

::: {layout="[65,35]"}
This indicator has 5 themes: the degree and quality of consultation with
society; the existence and quality of complaint mechanisms; government data
availability and accessibility; government data impact; right to information;
and publication of laws. There are 10 metrics (one more than in2017) and 6
data sources: the World Justice Project's Rule of Law Index (open government
theme); the UN E-Participation Index; the Bertelsmann Stiftung's SGIs; the
World Wide Web Foundation's Open DataBarometer; Open Knowledge International's
Global Open Data Index; and the OECD's OUR Government Data Index. It is
noteworthy that all 5 countries in this table are in Northern Europe. Norway's
top position reflects strong scores for most metrics. It achieves the maximum
score for the metric which assesses the extent to which governments consult
and negotiate with the public on policy issues. Norway also achieves the
maximum score for the metric on citizens' access to official information.
Denmark achieves the maximum score for 2 of the 3 metrics assessing the degree
and quality of government consultation with society on policy issues.

```{ojs, ind-opn}
indicator_bar("ind_opn")
```

:::

## Capabilities {#sec-capabilities}

::: {layout="[35,65]"}
```{ojs, ind-cap}
indicator_bar("ind_cap")
```

This attribute measures four themes: core capability (eg. problem solving,
numeracy and literacy skills); the use of core skills at work; organisational
skills (eg influencing and planning skills); and learning and development.
This attribute has 14 metrics – an increase of 10 since 2017. The sole data
source is the OECD's Programme for the International Assessment of Adult
Competencies (PIAAC) survey. It is notable that 3 of the top 5 countries for
this indicator are also in the top 5 for the entire InCiSE Index. New Zealand's
top position for this indicator reflects very strong scores for many of the
relevant metrics. This includes maximum scores for the metrics which assess
the use of IT skills and influencing skills in the workplace. The USA's score
for influencing skills is very strong as well, and both countries are well
ahead of the others in the top 5 for this metric. It is interesting to note
that all the top 5 countries' scores are very high for the readiness to
learn metric, most notably the USA, Denmark and Canada. Denmark also
achieves the maximum score for the degree of job-related learning metric,
while New Zealand performs very strongly.
:::

## Inclusiveness {#sec-inclusiveness}

::: {layout="[65,35]"}
This indicator has two themes: proportionate gender representation in the
civil service; and proportionate ethnic minority representation. There are 5
metrics and 3 data sources: the OECD's Government at a Glance (GaaG) survey
data on the share of women in central government and top management positions;
the University of Gothenburg's Quality of Government survey; and figures on
women's representation in government which are compared with statistics
collected and produced by the International Labour Organisation (ILO) on
women's participation in the labour force as a whole. To ensure relevant
comparison with the other metrics, ILO statistics and estimates for 2015
are used. Greece's very strong performance for this indicator reflects
high scores for the metric which assesses the proportion of women working in
the public sector. For the representation of ethnic and religious minorities
metric Poland has the highest score amongst the top 5 countries, while Romania
is only just behind. Poland also achieves the maximum score for the metric on
the proportion of women in senior government positions. Canada's score for
this metric is very strong as well and both countries' scores stand out from
the rest of the top 5 countries.

```{ojs, ind-inc}
indicator_bar("ind_inc")
```

:::
