project:
  type: book
  output-dir: docs
  pre-render: prepare.R

book:
  title: "InCiSE 2019: Results Report"
  date: "25 April 2019"
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - 00_contents.qmd
    - 00_readers_guide.qmd
    - 00_foreword.qmd
    - 00_exec_summary.qmd
    - 01_introduction.qmd
    - 02_incise_framework.qmd
    - 03_results.qmd
    - 04_00_country_profiles.qmd
    - 05_next_steps.qmd
  appendices:
    - A_indicator_definitions.qmd
    - B_data_sources.qmd
    - C_scores_rankings.qmd
    - X_static_content.qmd
    - Y_results_static.qmd
    - part: Z_00_country_profiles_static.qmd
      chapters:
        - Z_01_AUS.qmd
        - Z_01_AUS.qmd
        - Z_02_AUT.qmd
        - Z_03_BEL.qmd
        - Z_04_BGR.qmd
        - Z_05_CAN.qmd
        - Z_06_CHL.qmd
        - Z_07_CZE.qmd
        - Z_08_DEU.qmd
        - Z_09_DNK.qmd
        - Z_10_ESP.qmd
        - Z_11_EST.qmd
        - Z_12_FIN.qmd
        - Z_13_FRA.qmd
        - Z_14_GRC.qmd
        - Z_15_HRV.qmd
        - Z_16_HUN.qmd
        - Z_17_IRL.qmd
        - Z_18_ISL.qmd
        - Z_19_ISR.qmd
        - Z_20_ITA.qmd
        - Z_21_JPN.qmd
        - Z_22_KOR.qmd
        - Z_23_LTU.qmd
        - Z_24_LVA.qmd
        - Z_25_MEX.qmd
        - Z_26_NLD.qmd
        - Z_27_NOR.qmd
        - Z_28_NZL.qmd
        - Z_29_POL.qmd
        - Z_30_PRT.qmd
        - Z_31_ROU.qmd
        - Z_32_SVK.qmd
        - Z_33_SVN.qmd
        - Z_34_SWE.qmd
        - Z_35_CHE.qmd
        - Z_36_TUR.qmd
        - Z_37_GBR.qmd
        - Z_38_USA.qmd
  sidebar:
    collapse-level: 1
  navbar:
    background: dark
    right:
      - text: "More"
        menu:
          - text: "Read the InCiSE 2019 Technical Report"
            icon: book-half
            href: https://incise-project.github.io/incise2019-techreport/
          - text: "View the results dashboard"
            icon: bar-chart-fill
            href: https://incise-project.github.io/incise2019-dashboard/
          - text: "---"
          - text: "Download the PDF of this report"
            icon: file-earmark-pdf
            href: incise2019_results_report.pdf
          - text: "View the source code of this report"
            icon: github
            href: https://github.com/incise-project/incise2019-results/
          - text: "---"
          - text: "Go to the InCiSE Project homepage"
            icon: house-fill
            href: https://incise-project.github.io/
  cover-image: figures/incise2019_results_cover.png
  url: https://incise-project.github.io/incise2019-results/
  keyword: international civil service effectiveness, civil service, government,
    effectiveness, performance, public management, public governance

execute:
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - custom.scss
    fig-cap-location: top
    fig-format: svg
    fig-responsive: true
    tbl-cap-location: top
    reference-location: margin
    strip-comments: true
    number-depth: 2
