## Welcome {.unnumbered}

This is an HTML version of the International Civil Service Effectiveness
(InCiSE) Index 2019 Results Report,
[originally published](https://www.bsg.ox.ac.uk/news/new-index-ranks-uk-civil-service-top-followed-new-zealand-and-canada)
in April 2019 by the InCiSE Partners.

This report summarises the results of the 2019 InCiSE Index, for the index
overall, its constituent indicators and summaries of country performance. For
details on the methodology behind the InCiSE Index please see the
[Technical Report](https://incise-project.github.io/incise2019-techreport/).

From 2016 to 2019, the
[International Civil Service Effectiveness (InCiSE) project](https://www.bsg.ox.ac.uk/incise)
was a collaboration between the
[Blavatnik School of Government](https://www.bsg.ox.ac.uk) and the
[Institute for Government](http://instituteforgovernment.org.uk).
It was supported by the UK Civil Service (through the
[Cabinet Office](https://www.gov.uk/cabinetoffice)) and funded by the
[Open Society Foundations](https://www.opensocietyfoundations.org).

The Blavatnik School of Government is re-establishing the InCiSE project with
the aim of publishing a new edition of the InCiSE Index in 2024. To support
engagement with stakeholders the School is re-publishing the 2019 project
outputs (this Results Report, the
[Technical Report](https://incise-project.github.io/incise2019-techreport/)
and interactive data visualisations) in more modern and user friendly formats.

### Differences from the original 2019 publication

Some typographic errors have been corrected as part of the re-publication of
this report. There have also been some changes to the tables and figures when
compared to the original report, these are largely for layout purposes.
Footnotes have been added to charts, tables and chapters to indicate changes
in content and differences in numbering.

Please note that @sec-country-profiles of this web book provides an
interactive version of the report content - non-interactive versions of the
country profiles are available ...

You can also download and read the
[original PDF publication](incise2019_results_report.pdf).

## Preface to the original report

Two reports have been published covering the 2019 edition of the InCiSE Index:

* The Results Report (this report) provides an overview of the overall results
  of the InCiSE Index, and a summary for each country covered by the Index.
* The [Technical Report](https://incise-project.github.io/incise2019-techreport/)
  provides the methodology of the InCiSE Index, it includes details fo the data
  sources, transformations, imputation, and weightings.

Users are free to copy, download and print InCiSE content and findings for
their own use. Excerpts from InCiSE reports and publications may also be used,
but must be appropriately referenced.

The Index is comprised of a variety of other data sources. Reuse is not
applicable to data subject to intellectual property rights of third parties.
Please refer to other organisations’ corresponding websites and data licensing
restrictions to ensure compliance with their data limitations. Details of data
sources can be found in Appendix B at the end of this report. Every effort has
been made to adhere to third party data regulations.

### Acknoweldgements

Our thanks go to those who have given their time to shape this second
publication of the InCiSE Index. This has included substantial contributions
made by academics, think-tanks and civil servants, past and present. Thanks
also go to those organisations who have allowed us once again to use their data
in the InCiSE Index, as well as their ideas and support for the overall project.

## Citation

Please continue to refer to and cite the original 2019 publication as the
canonical version of the report:

> InCiSE Partners (2019) The International Civil Service Effectiveness (InCiSE)
> Index: Results Report 2019, Oxford: Blavatnik School of Government,
> University of Oxford, [https://www.bsg.ox.ac.uk/incise](https://www.bsg.ox.ac.uk/incise)
